# Generated by Django 4.2.1 on 2023-05-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='completed',
            field=models.ManyToManyField(related_name='completed_homeworks', to='tutorapp.student'),
        ),
    ]
