# Generated by Django 4.2.1 on 2023-05-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0002_homework_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_answers/'),
        ),
    ]
