# Generated by Django 4.2.1 on 2023-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0005_remove_homework_description_remove_student_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
