# Generated by Django 4.2.1 on 2023-05-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0007_alter_student_age_alter_student_parent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Нет имени', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(default='Нет имени', max_length=100),
        ),
    ]
