# Generated by Django 4.2.1 on 2023-05-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0008_alter_student_name_alter_tutor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='homeworks',
            field=models.ManyToManyField(null=True, related_name='tutors', to='tutorapp.homework'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='qualification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorapp.subject'),
        ),
    ]
